config/routes.rb
Rails.application.routes.draw do
  root 'index#input'
  get 'index/input'
  get 'index/output'
  get 'session/login'
  post 'session/create'
  get 'session/logout'
  resources :users
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

  def update_last_login_at
    self.last_login_at = DateTime.now
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionHelper

  before_action :require_login

  private

  def require_login
    unless signed_in?
      flash[:danger] = 'Требуется логин'
      redirect_to session_login_url
    end
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def input

  end

  def output
    @mas=func(params[:value])
  end

  private
  def func(input_line)
   puts ">>>>>>>>>>>>#{input_line}"
    if input_line.nil?
      @error = 'Некорректный ввод' 
    elsif input_line.scan(/\D/).any? || input_line.empty?  
      @error = 'Некорректный ввод'
    elsif input_line.to_f<0
      @error = 'Некорректный ввод'
    else
      a = input_line.to_f
      x=a
      array=[]
      array.push(x)
       while ((x**2-a)/a)>=0.001 
         x1=(1/2.0)*(x+(a/x)) 
         x=x1.round(3)
         array.push(x)
       end
      array
     end
   end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :require_login, only: %i[login create]

  def login; end

  def create
    user = User.find_by(username: params[:username])

    if user&.authenticate(params[:password])
      p 'Login'
      sign_in user
      redirect_to root_url
    else
      flash.now[:danger] = 'Неверный логин или пароль'
      redirect_to session_login_url
    end
  end

  def logout
    sign_out
    redirect_to session_login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :require_login, only: %i[new create]
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :last_login_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/session_helper.rb
module SessionHelper
    def sign_in(user)
        cookies.signed[:user_id] = { value: user.id, expires: 10.days }
        user.update_last_login_at
        self.current_user = user
      end
    
      def signed_in?
        !current_user.nil?
      end
    
      def sign_out
        cookies.signed[:user_id] = nil
        self.current_user = nil
      end
    
      def current_user=(user)
        @current_user = user
      end
    
      def current_user
        @current_user ||= User.find_by(id: cookies.signed[:user_id])
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/index/input.html.erb
<p>Введите число</p>
<form action="<%= index_output_url%>">
   <input name="value" placeholder="1">
   <input type="submit">
</form>
<%= link_to "SignOut", session_logout_url %>
<%= link_to "AllUsers", users_url %>

app/views/index/output.html.erb
<h1>Результат</h1>
<% if @error%>
   <p><%= @error %></p>
<% else %>

   <h4>Последний элемент таблицы будет результатом вычислений</h4>
   <table >
   <tr>
     <th>Номер элемента</th>
     <th>Значение</th>
   </tr>

   <% @mas.each_with_index do |r, idx|%>

   <tr>
     <td><%= idx+1 %></td>
     <td><%= r %></td>
   </tr>

   <% end %>
   </table>
<% end %>

<%= link_to "Back to input", index_input_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= link_to "Back to input", index_input_url %>
    <%= link_to "SignOut", session_logout_url %>
  </body>
</html>

app/views/session/login.html.erb
<%= form_with url: session_create_url, method: :post, local: true do |f| %>
    <%= f.text_field :username, required: true, label: 'Логин' %>
    <%= f.password_field :password, required: true, label: 'Пароль' %>
    <%= f.submit :password, required: true %>
<% end %>
<%= link_to 'Registration', new_user_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username, style: "display: block"%>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password, required: true %>
  </div>

  <div class="field">
     <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation, required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p style="color: green" id="notice"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <p>Username: <%=user.username%></p>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>


<p>
  <strong>Last login at:</strong>
  <%= @user.last_login_at %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<%= button_to "Destroy this user", @user, method: :delete %>